version: '3.9'
services:

#### BACKEND ####
  api-gateway:
    build:
      context: .
      dockerfile: ./.docker/backend/Dockerfile.api-gateway
    ports:
      - "3000:3000" # Map le port local 3000 au port du container
    # depends_on:
    #   - user-microservice
    #   - chat-microservice
    #   - notes-microservice
    networks:
      - app-network
    volumes:
      - ./backend/apps/api-gateway:/usr/src/app
      - /usr/src/app/node_modules

  # user-microservice:
  #   build:
  #     context: .
  #     dockerfile: ./.docker/backend/Dockerfile.user-microservice
  #   ports:
  #     - "3001:3000"
  #   networks:
  #     - app-network
  #   volumes:
  #     - ./backend/apps/user-microservice:/usr/src/app
  #     - /usr/src/app/node_modules

  # chat-microservice:
  #   build:
  #     context: .
  #     dockerfile: ./.docker/backend/Dockerfile.chat-microservice
  #   ports:
  #     - "3002:3000"
  #   networks:
  #     - app-network
  #   volumes:
  #     - ./backend/apps/chat-microservice:/usr/src/app
  #     - /usr/src/app/node_modules

  # notes-microservice:
  #   build:
  #     context: .
  #     dockerfile: ./.docker/backend/Dockerfile.notes-microservice
  #   ports:
  #     - "3003:3000"
  #   networks:
  #     - app-network
  #   volumes:
  #     - ./backend/apps/notes-microservice:/usr/src/app
  #     - /usr/src/app/node_modules

networks:
  app-network:
    driver: bridge

