version: '3.9'
services:
    #### BACKEND ####
    api-gateway:
        build:
            context: ./
            dockerfile: ./.docker/backend/Dockerfile.api-gateway
        ports:
            - '3000:3000' # Map le port local 3000 au port du container
        depends_on:
            user-microservice:
                condition: service_started
            chat-microservice:
                condition: service_started
            notes-microservice:
                condition: service_started
            rabbitmq:
                condition: service_healthy
        networks:
            - app-network
        env_file:
            - ./global.env
        volumes:
            - ./backend/apps/api-gateway:/usr/src/app
            - /usr/src/app/node_modules
        develop:
            watch:
                - action: sync
                - path: ./backend/apps/api-gateway
                - target: /usr/src/app

    user-microservice:
        build:
            context: .
            dockerfile: ./.docker/backend/Dockerfile.user-microservice
        ports:
            - '3001:3000'
        depends_on:
            rabbitmq:
                condition: service_healthy
        networks:
            - app-network
        env_file:
            - ./global.env
        volumes:
            - ./backend/apps/user-microservice:/usr/src/app
            - /usr/src/app/node_modules

    chat-microservice:
        build:
            context: .
            dockerfile: ./.docker/backend/Dockerfile.chat-microservice
        ports:
            - '3002:3000'
        depends_on:
            rabbitmq:
                condition: service_healthy
        networks:
            - app-network
        env_file:
            - ./global.env
        volumes:
            - ./backend/apps/chat-microservice:/usr/src/app
            - /usr/src/app/node_modules

    notes-microservice:
        build:
            context: .
            dockerfile: ./.docker/backend/Dockerfile.notes-microservice
        ports:
            - '3003:3000'
        depends_on:
            rabbitmq:
                condition: service_healthy
        networks:
            - app-network
        env_file:
            - ./global.env
        volumes:
            - ./backend/apps/notes-microservice:/usr/src/app
            - /usr/src/app/node_modules

    rabbitmq:
        image: rabbitmq:3-management-alpine
        container_name: 'rabbitmq'
        ports:
            - '5672:5672'
            - '15672:15672'
        volumes:
            - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
            - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
        networks:
            - app-network
        healthcheck:
            test: ['CMD', 'rabbitmq-diagnostics', 'ping']
            interval: 5s
            timeout: 10s
            retries: 10

networks:
    app-network:
        driver: bridge
