# Utiliser une image de base pour Node.js
FROM node:23

# Définir le répertoire de travail
WORKDIR /app

# Copier les fichiers package.json et package-lock.json
COPY frontend/main/package*.json ./

# Installer les dépendances
RUN npm install

# Copier le reste des fichiers de l'application
COPY frontend/main/ ./

# Construire l'application
RUN npm run build

# Exposer le port de l'application
EXPOSE 5173

# Démarrer l'application
CMD ["npm", "run", "preview", "--", "--host", "0.0.0.0"]

