# Base image
FROM node:23

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json
COPY backend/package*.json ./

# Install dependencies
RUN npm install

# Copy the source code of the current service
COPY backend/apps/chat-microservice ./usr/src/app

# Copy the shared libraries
COPY backend/libs ./usr/src/app/libs

# Expose the port the app runs on
EXPOSE 3000

# Start the application
CMD ["npm", "run", "start:microservice"]
